version: 0.2

phases:
  install:
    commands:
      - echo Installing Python dependencies (if any)
  build:
    commands:
      - echo "Listing files in current directory:"
      - ls -l
      - echo "Running script..."
      - python3 "dice guess game.py"

artifacts:
  files:
    - '**/*'
