version: 0.2

phases:
  install:
    commands:
      - echo Installing Python dependencies (if any)
  build:
    commands:
      - echo Running Python script...
      - python3 dice_guess_game.py

artifacts:
  files:
    - '**/*'
